### ISSUE TITLE
Bug: double events in Chrome, missing data in Firefox/Safari

### ISSUE THREAD

**Issue by ryantownsend** [keithamus/invokers-polyfill#34]
I'm seeing some unexpected behavior with this polyfill in all browsers:

1. Google Chrome (Canary 123.0.6268.0) is outputting the `invoke` event twice
2. Firefox (122.0) and Safari (TP Release 186, Safari 17.4, WebKit 19618.1.10.1.1) only render the `isTrusted: false` event, where `action` is missing

### Demonstration

I've built a demo here: https://jsbin.com/gudesegohe/edit?html,output

### Workaround

For now I'm just returning early when `event.isTrusted == true` to skip the duplicate event, and replacing `event.action` with `event.invoker.getAttribute("invoketarget")`

#### Chrome

<img width="1000" alt="Screenshot 2024-01-28 at 16 27 15" src="https://github.com/keithamus/invokers-polyfill/assets/12299/b6577fa3-eff0-4458-990d-8e75493ab2b3">

#### Safari

<img width="1014" alt="Screenshot 2024-01-28 at 16 27 46" src="https://github.com/keithamus/invokers-polyfill/assets/12299/70f2be69-1517-4889-97c1-0d2952dd2a27">

#### Firefox

<img width="1202" alt="Screenshot 2024-01-28 at 16 28 46" src="https://github.com/keithamus/invokers-polyfill/assets/12299/8a03da51-8b2d-4908-922d-d6ec2f4c042d">

**Comment by keithamus** [comment]
The `isTrusted === true` events are coming from the browser (it is impossible to set `isTrusted = true` from JS). It seems like the feature detection may not be working properly, to avoid applying the polyfill in Chrome.

**Comment by keithamus** [comment]
[v0.1.1](https://github.com/keithamus/invokers-polyfill/releases/tag/v0.1.1) fixed the second issue. Now the polyfilled events will correctly provide the right `action`. 

I am not sure what to do about the feature detection as I'm unable to reproduce. I'll investigate some more.

**Comment by ryantownsend** [comment]
@keithamus thanks for the update! If there's anything I can do to help debug the feature detection somehow, let me know.

**Comment by keithamus** [comment]
I'm struggling to reproduce getting both events. The feature detection is:

https://github.com/keithamus/invokers-polyfill/blob/c6a91694e6ccd720a9128019822993f5ab877f95/invoker.js#L3-L5

If you run that expression in your browser does it return `true`?

**Comment by keithamus** [comment]
Oh :facepalm: I just realised it is dispatching events with the flag turned off, but the feature detection is missing because the globals aren't available. This is a bug in Chrome that will need to be fixed.

**Comment by ryantownsend** [comment]
Ah good find 🕵️‍♂️ I bet that was a head-scratcher!

**Comment by keithamus** [comment]
[v1.1.2](https://github.com/keithamus/invokers-polyfill/releases/tag/v0.1.2) fixes the Chrome issue.

I'll mark this as closed, as I think it addresses both issues. Please do raise new issues if you find them!
