### ISSUE TITLE
Bug: Mutation Observer doesn't handle new nodes being added

### ISSUE THREAD

**Issue by ryantownsend** [keithamus/invokers-polyfill#35]
The mutation observer, doesn't handle new nodes being added to the page:

https://github.com/keithamus/invokers-polyfill/blob/d410b54b8a37dbd18fcfa2eeb40b071863bbec0b/invoker.js#L238-L249

I presume this functionality would be offered by the native implementation?

If so, this suggestion will add in support for new DOM nodes, I'm not sure how performant it is, given it's listening on the whole document for newly-added nodes and querying their whole DOM tree on any change:

```js
  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      // handle attribute changes
      if (mutation.type === "attributes") {
        if (
          mutation.attributeName === "invoketarget" &&
          mutation.target.invokeTargetElement
        ) {
          setupInvokeListeners(mutation.target);
        }
      // handle new DOM elements
      } else if (mutation.type === "childList" && mutation.addedNodes.length > 0) {
        for (const addedNode of mutation.addedNodes) {
          if (addedNode.nodeType != Node.ELEMENT_NODE) {
            continue;
          }
          if (addedNode.matches("[invoketarget]")) {
            setupInvokeListeners(addedNode);
          }
          for (const addedChildNode of addedNode.querySelectorAll("[invoketarget]")) {
            setupInvokeListeners(addedChildNode);
          }
        }
      }
    }
  });
```

If this is expected functionality, either I can create a PR or you can handle that @keithamus 👍

**Comment by keithamus** [comment]
Just moved to using a global listener, avoiding the need for MO entirely.
