### ISSUE TITLE
Minified build out-of-date

### ISSUE THREAD

**Issue by ryantownsend** [keithamus/invokers-polyfill#46]
The current minified version of the build is 5 commits out-of-date and broken in Canary. Using the non-minified version seems to work fine, so it appears that it purely needs regenerating.

**Comment by keithamus** [comment]
Is this the minified file from git? Or from the published package? It seems like the build runs the minify step - so I imagine it's okay?

**Comment by keithamus** [comment]
I've removed the minified version from git, to ensure folks use the one in the package. A URL like https://unpkg.com/invokers-polyfill@0.4.6/invoker.min.js can be used to get the minified version.

Just in case anyone was using the raw github URL, I'd recommend not doing that as there's no guarantee those files will always exist (a github repo can have a force push or tag removal which can invalidate a raw github URL).
