### ISSUE TITLE
This only intends to covers Invoker Commands, not interest invokers, right?

### ISSUE THREAD

**Issue by SilentImp** [keithamus/invokers-polyfill#49]
This only intends to covers Invoker Commands, not interest invokers, right?

**Comment by keithamus** [comment]
Correct. Interest invokers are still very much in the air, but also the differences between them will likely warrant its own polyfill (if the feature-set is even polyfillable). Rest assured though I'll be interested in providing a polyfill for interest invokers when we've got a more concrete story for them!
